--- #YAML:1.0
name:               Parse-CPAN-Cached
version:            0.02
version_from:       lib/Parse/CPAN/Cached.pm
abstract:           Parse CPAN meta files and cache the results
author:
    - Murray <sysmon@cpan.org>
license:            perl
installdirs:        site
requires:
distribution_type:  module
generated_by:       ExtUtils::MakeMaker version 6.30_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
